### ISSUE TITLE
Add instructions for connecting to LinkSquare

### ISSUE THREAD

**Issue by jmh579** [PhenoApps/Prospector#12]
Write out or diagram user instructions/tutorial for how to connect to the LS to the app. Include option to hide instructions (possibly as checkbox). 

Example from the original LS app:

<p float="left">
  <img src="https://user-images.githubusercontent.com/33294076/85876478-c623ab00-b7a3-11ea-8be7-983cefcdff32.png" width="45%" /> 
  <img src="https://user-images.githubusercontent.com/33294076/85876476-c4f27e00-b7a3-11ea-997c-f155ede20047.png" width="45%" />
</p>

**Comment by trife** [comment]
Related to #9

**Comment by trife** [comment]
![Screenshot_20210422-090607](https://user-images.githubusercontent.com/1869534/115728335-0ca55000-a34a-11eb-8848-4a6d9ecdfa7c.png)
