### ISSUE TITLE
Prospector data comparison with LS app data

### ISSUE THREAD

**Issue by MatteoMartina** [PhenoApps/Prospector#132]
Dear team,
we phenotyped our population using your app, while our colleagues in another university used the LS app...
In the LS app there is the option to normalize the data (SNV function), while in Prospector I cannot find such option.

In order to evaluate the data and compare them with our colleagues, I need to be sure that the spectral data from Prospector are **NOT normalized** with SNV.

Could you help me?

Best,
Matteo

**Comment by chaneylc** [comment]
Hello Matteo,
The data stored in Prospector is not normalized, hope this helps :)
